### ISSUE TITLE
I am still unable to produce a map for Xiaomi X20 Max

### ISSUE THREAD

**Issue by fitsou** [maksp86/HA-custom-components-Xiaomi-Cloud-Map-Extractor-Ijai-Support#1]
### Checklist

- [x] I have updated the integration to the latest version available
- [x] I have checked if the problem is already reported

### The problem

Hello and happy Friday.
I'm using a Xiaomi X20 Max (model: `xiaomi.vacuum.d109gl`) with your Xiaomi Cloud Map Extractor integration.
Since this model was not working with the default version, I manually downloaded the ZIP of the and extracted it into `/config/custom_components/xiaomi_cloud_map_extractor`.
I used this configuration in Configuration.yaml:

```
#Xiaomi X20 Max Setup
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.111
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_username
    password: !secret xiaomi_password
    country: de  # Your Xiaomi cloud region; 'de' is correct for Greece
    name: Xiaomi X20 Max Map
    draw: ['all']
    map_transformation:
      scale: 1
    attributes:
      - calibration_points
```

But in States in Attributes I see used_api: null

![Image](https://github.com/user-attachments/assets/ccc643aa-eeae-487f-89bd-ef6e4258553b)

I am not an expert but I believe The the null shouldn't be there.

In any case I still cannot see the map

![Image](https://github.com/user-attachments/assets/24e4d976-6857-4533-8111-8d11c255af30)

### What version of an integration has described problem?

v2.2.3

### What vacuum model do you have problems with?

xiaomi.vacuum.d109gl

### What version of Home Assistant do you use?

2025.5.3

### What type of installation are you running?

Home Assistant OS

### Camera's configuration

```yaml
#Xiaomi X20 Max Setup
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.1.111
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_username
    password: !secret xiaomi_password
    country: de  # Your Xiaomi cloud region; 'de' is correct for Greece
    name: Xiaomi X20 Max Map
    draw: ['all']
    map_transformation:
      scale: 1
    attributes:
      - calibration_points
```

### Errors shown in the HA logs (if applicable)

```shell

```
